# Figure out which OS we're running
if [[ $(uname -s) -eq "Linux" ]]; then
  export OS="Linux"
else
  export OS="MacOS"
fi

# Needed on some systems
export LANG=en_US.UTF-8

# Adding extra stuff to path
export PATH=$HOME/.local/bin:$HOME/.bin:$HOME/bin:/usr/local/bin:$PATH
export VIMRC=$HOME/etc/neovim/init.vim

# Aliases
alias t="tmux"
alias doc="docker-compose"
alias dcsh="docker-compose exec api bash"

alias dotfiles="cd ~/etc && ls"
alias zconf="nvim ~/etc/zprezto/runcoms/zshrc"
alias reload="source ~/.zshrc"
alias vimconf="nvim ~/etc/nvim/init.vim"

alias enc='openssl enc -aes-256-cbc -in "$@"'
alias dec='openssl enc -d -aes-256-cbc -in "$@"'

# nvim <3
export EDITOR="nvim"
export VISUAL="nvim"
export XDG_CONFIG_HOME="$HOME/etc"

export XDG_CONFIG_HOME="$HOME/etc"

# z - jump around
. $HOME/etc/z/z.sh

# Enable Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Secret env variables
if [[ -f "$HOME/.env" ]]; then
  source $HOME/.env
fi
export NVM_DIR="$HOME/etc/nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
