# Figure out which OS we're running
if [[ $(uname -s) -eq "Linux" ]]; then
  export OS="Linux"
else
  export OS="MacOS"
fi

# Needed on some systems
export LANG=en_US.UTF-8

# Adding extra stuff to path
export PATH=$HOME/.local/bin:$HOME/.bin:$HOME/bin:/usr/local/bin:$PATH

# Aliases
alias t="tmux"
alias doc="docker-compose"
alias dcsh="docker-compose exec api bash"

alias dotfiles="cd ~/etc && ls"
alias zconf="vim ~/etc/zprezto/runcoms/zshrc"
alias reload="source ~/.zshrc"
alias vimconf="vim ~/etc/vim/vimrc"

alias enc='openssl enc -aes-256-cbc -in "$@"'
alias dec='openssl enc -d -aes-256-cbc -in "$@"'

# vim <3
export EDITOR="vim"
export VISUAL="vim"

# z - jump around
. $HOME/etc/z/z.sh

# Enable Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Secret env variables
if [[ -s "~/.env" ]]; then
  source ~/.env
fi
